camera/horizontal_fov: 360.0
camera/vertical_fov: 90.0

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 2.5
system/bbx/overshoot: 0.5

aep/gain/r_min: 0
aep/gain/r_max: 5
aep/gain/zero: 25
aep/gain/lambda: 0.75
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 3
aep/tree/max_sampling_radius: 100
aep/tree/initial_iterations: 10
aep/tree/cutoff_iterations: 200

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-3.0, -3.0, 0.0]
boundary/max: [ 45.0,  53.0, 78.0]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"
